# Generated by Django 6.0.6 on 2026-06-29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_cascade_delete_tasks_on_competency'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessmentresult',
            name='mastery_status',
            field=models.CharField(
                blank=True,
                choices=[
                    ('Not Yet Demonstrated', 'Not Yet Demonstrated'),
                    ('Developing', 'Developing'),
                    ('Proficient', 'Proficient'),
                    ('Mastery', 'Mastery'),
                ],
                default='Developing',
                max_length=50,
                null=True,
            ),
        ),
    ]
