# Generated by Django 6.0.6 on 2026-06-30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_learnerprofile_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learnerprofile',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
    ]