# Generated by Django 6.0.6 on 2026-06-30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_learnerprofile_date_of_birth'),
    ]

    operations = [
        migrations.AddField(
            model_name='competency',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
    ]