# Generated by Django 6.0.6 on 2026-06-30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_competency_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='competency',
            old_name='description',
            new_name='learning_outcome',
        ),
    ]