# Generated by Django 6.0.6 on 2026-06-30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_rename_competency_description_to_learning_outcome'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assessmenttask',
            old_name='task_title',
            new_name='task_name',
        ),
        migrations.RenameField(
            model_name='assessmenttask',
            old_name='task_description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='assessmenttask',
            old_name='teacher',
            new_name='created_by',
        ),
        migrations.AlterField(
            model_name='assessmenttask',
            name='task_date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AddField(
            model_name='assessmenttask',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
    ]