# Generated by Django 6.0.6 on 2026-06-30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_rename_result_fields_and_add_metadata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessmenttask',
            name='task_date',
            field=models.DateField(),
        ),
    ]