# Generated by Django 6.0.6 on 2026-06-30 10:38

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_alter_assessmenttask_task_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assessmenttask',
            options={'ordering': ['-created_at', 'task_name']},
        ),
        migrations.AddField(
            model_name='assessmentresult',
            name='assessment_date',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
        migrations.AlterField(
            model_name='assessmentresult',
            name='cbc_rating',
            field=models.CharField(choices=[('Exceeding Expectations', 'Exceeding Expectations'), ('Meeting Expectations', 'Meeting Expectations'), ('Developing', 'Developing'), ('Not Yet Demonstrated', 'Not Yet Demonstrated')], max_length=40),
        ),
        migrations.AlterField(
            model_name='assessmentresult',
            name='mastery_status',
            field=models.CharField(choices=[('Not Yet Demonstrated', 'Not Yet Demonstrated'), ('Developing', 'Developing'), ('Proficient', 'Proficient'), ('Mastery', 'Mastery')], default='Developing', max_length=50),
        ),
        migrations.AlterField(
            model_name='assessmenttask',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='assessmenttask',
            name='task_name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='competency',
            name='learning_outcome',
            field=models.TextField(),
        ),
    ]
