# Generated by Django 6.0.6 on 2026-07-04 03:48

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_restore_assessment_date_on_assessmentresult'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessmentresult',
            name='cbc_rating',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='assessmenttask',
            name='task_date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.CreateModel(
            name='LearnerReportFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback', models.TextField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('competency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_feedbacks', to='core.competency')),
                ('learner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_feedbacks', to='core.learnerprofile')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='written_report_feedbacks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
                'constraints': [models.UniqueConstraint(fields=('learner', 'competency'), name='unique_learner_competency_report_feedback')],
            },
        ),
    ]
