# Generated by Copilot on 2026-07-04

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_learnerreportfeedback_assessment_results_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessmenttask',
            name='task_date',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
    ]