# Generated by Django 6.0.6 on 2026-07-04 14:36

from django.db import migrations, models


def populate_teacher_ids(apps, schema_editor):
    UserAccount = apps.get_model('core', 'UserAccount')
    db_alias = schema_editor.connection.alias
    teacher_accounts = UserAccount.objects.using(db_alias).filter(role='Teacher')
    for account in teacher_accounts:
        if account.teacher_id is None:
            account.teacher_id = account.user_id
            account.save(update_fields=['teacher_id'])


def unpopulate_teacher_ids(apps, schema_editor):
    UserAccount = apps.get_model('core', 'UserAccount')
    db_alias = schema_editor.connection.alias
    UserAccount.objects.using(db_alias).filter(role='Teacher').update(teacher_id=None)


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_alter_assessmenttask_task_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='teacher_id',
            field=models.PositiveIntegerField(blank=True, editable=False, null=True, unique=True),
        ),
        migrations.RunPython(populate_teacher_ids, unpopulate_teacher_ids),
    ]
