# Generated by Django 6.0.6 on 2026-07-06 07:47

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


def backfill_teacher_learner_records(apps, schema_editor):
    LearnerProfile = apps.get_model('core', 'LearnerProfile')
    TeacherLearnerRecord = apps.get_model('core', 'TeacherLearnerRecord')
    AssessmentResult = apps.get_model('core', 'AssessmentResult')
    LearnerReportFeedback = apps.get_model('core', 'LearnerReportFeedback')

    for result in AssessmentResult.objects.filter(teacher_learner_record__isnull=True):
        if not result.created_by_id or not result.learner_id:
            continue
        record, _ = TeacherLearnerRecord.objects.get_or_create(
            teacher_id=result.created_by_id,
            learner_profile_id=result.learner_id,
        )
        result.teacher_learner_record_id = record.id
        result.save(update_fields=['teacher_learner_record'])

    for feedback in LearnerReportFeedback.objects.filter(teacher_learner_record__isnull=True):
        if not feedback.teacher_id or not feedback.learner_id:
            continue
        record, _ = TeacherLearnerRecord.objects.get_or_create(
            teacher_id=feedback.teacher_id,
            learner_profile_id=feedback.learner_id,
        )
        feedback.teacher_learner_record_id = record.id
        feedback.save(update_fields=['teacher_learner_record'])

    linked_pairs = set(
        TeacherLearnerRecord.objects.values_list('teacher_id', 'learner_profile_id')
    )
    for learner in LearnerProfile.objects.filter(created_by__isnull=False, user_account__isnull=True):
        pair = (learner.created_by_id, learner.id)
        if pair in linked_pairs:
            continue
        TeacherLearnerRecord.objects.create(teacher_id=learner.created_by_id, learner_profile_id=learner.id)
        linked_pairs.add(pair)


def noop_reverse(apps, schema_editor):
    return None


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_useraccount_teacher_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherLearnerRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
            ],
            options={
                'ordering': ['learner_profile__full_name'],
            },
        ),
        migrations.RemoveConstraint(
            model_name='assessmentresult',
            name='unique_learner_task_result',
        ),
        migrations.RemoveConstraint(
            model_name='learnerreportfeedback',
            name='unique_learner_competency_report_feedback',
        ),
        migrations.AddField(
            model_name='teacherlearnerrecord',
            name='learner_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_records', to='core.learnerprofile'),
        ),
        migrations.AddField(
            model_name='teacherlearnerrecord',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_learner_records', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='assessmentresult',
            name='teacher_learner_record',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='results', to='core.teacherlearnerrecord'),
        ),
        migrations.AddField(
            model_name='learnerreportfeedback',
            name='teacher_learner_record',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='report_feedbacks', to='core.teacherlearnerrecord'),
        ),
        migrations.RunPython(backfill_teacher_learner_records, noop_reverse),
        migrations.AddConstraint(
            model_name='assessmentresult',
            constraint=models.UniqueConstraint(condition=models.Q(('teacher_learner_record__isnull', False)), fields=('teacher_learner_record', 'task'), name='unique_teacher_learner_task_result'),
        ),
        migrations.AddConstraint(
            model_name='learnerreportfeedback',
            constraint=models.UniqueConstraint(condition=models.Q(('teacher_learner_record__isnull', False)), fields=('teacher_learner_record', 'competency'), name='unique_teacher_learner_competency_report_feedback'),
        ),
        migrations.AddConstraint(
            model_name='teacherlearnerrecord',
            constraint=models.UniqueConstraint(fields=('teacher', 'learner_profile'), name='unique_teacher_learner_record'),
        ),
    ]
