# Generated by Django 6.0.6 on 2026-07-06 08:24

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_teacherlearnerrecord_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherLearnerCompetencyAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('competency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_assignments', to='core.competency')),
                ('teacher_learner_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competency_assignments', to='core.teacherlearnerrecord')),
            ],
            options={
                'ordering': ['competency__competency_code'],
                'constraints': [models.UniqueConstraint(fields=('teacher_learner_record', 'competency'), name='unique_teacher_learner_competency_assignment')],
            },
        ),
    ]
