# Generated by Django 6.0.6 on 2026-06-24 12:33

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Competency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('competency_code', models.CharField(max_length=20, unique=True)),
                ('competency_name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_competencies', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['competency_code'],
            },
        ),
        migrations.CreateModel(
            name='AssessmentTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_title', models.CharField(max_length=100)),
                ('task_description', models.TextField(blank=True)),
                ('task_date', models.DateField()),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_tasks', to=settings.AUTH_USER_MODEL)),
                ('competency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tasks', to='core.competency')),
            ],
            options={
                'ordering': ['-task_date', 'task_title'],
            },
        ),
        migrations.CreateModel(
            name='UserAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('Administrator', 'Administrator'), ('Teacher', 'Teacher'), ('Learner', 'Learner')], max_length=20)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='account', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['user__username'],
            },
        ),
        migrations.CreateModel(
            name='LearnerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admission_number', models.CharField(max_length=20, unique=True)),
                ('full_name', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10)),
                ('class_name', models.CharField(max_length=50)),
                ('date_of_birth', models.DateField()),
                ('user_account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='learner_profile', to='core.useraccount')),
            ],
            options={
                'ordering': ['full_name'],
            },
        ),
        migrations.CreateModel(
            name='AssessmentResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('rating', models.CharField(max_length=30)),
                ('feedback', models.TextField(blank=True)),
                ('assessment_date', models.DateField()),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recorded_results', to=settings.AUTH_USER_MODEL)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='core.assessmenttask')),
                ('learner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='core.learnerprofile')),
            ],
            options={
                'ordering': ['-assessment_date'],
                'constraints': [models.UniqueConstraint(fields=('learner', 'task'), name='unique_learner_task_result')],
            },
        ),
    ]
