# Generated by Django 6.0.6 on 2026-06-25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_backfill_mathematics_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessmenttask',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assessment_tasks', to='core.subject'),
        ),
    ]
