# Generated by Django 6.0.6 on 2026-06-25

from django.db import migrations



def backfill_assessment_task_subject(apps, schema_editor):
    Subject = apps.get_model('core', 'Subject')
    AssessmentTask = apps.get_model('core', 'AssessmentTask')

    mathematics = Subject.objects.filter(subject_name__iexact='Mathematics').first()
    if not mathematics:
        mathematics = Subject.objects.filter(subject_code='MATH').first()
    if not mathematics:
        mathematics = Subject.objects.first()

    for task in AssessmentTask.objects.filter(subject__isnull=True).select_related('competency'):
        inferred_subject = getattr(task.competency, 'subject_id', None)
        if inferred_subject:
            task.subject_id = inferred_subject
        elif mathematics:
            task.subject = mathematics
        task.save(update_fields=['subject'])


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_assessmenttask_subject'),
    ]

    operations = [
        migrations.RunPython(backfill_assessment_task_subject, migrations.RunPython.noop),
    ]
