# Generated by Django 6.0.6 on 2026-06-28 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_backfill_assessmenttask_subject'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='competency',
            name='subject',
        ),
    ]
