# Generated by Django 6.0.6 on 2026-06-28 13:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_subject_from_competency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessmenttask',
            name='competency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='core.competency'),
        ),
    ]
